include:
  - project: "waldur/waldur-pipelines"
    file: "/templates/stages.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/test/check-merge-compatibility.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/release/sync-to-github.yml"

variables:
  GITHUB_OPENNODE_REPO_URL: "git@github.com:opennode/waldur-docs.git"
  GITHUB_WALDUR_REPO_URL: "git@github.com:waldur/waldur-docs.git"

Test mkdocs:
  image: registry.hpc.ut.ee/mirror/library/python:3.8-buster
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - pip install -r requirements.txt
    - mkdocs build --strict --verbose --site-dir test

Build pages:
  image: registry.hpc.ut.ee/mirror/library/python:3.8-buster
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    # Ignore if `github_*` remote already exists
    - git remote add github_opennode $GITHUB_OPENNODE_REPO_URL || true
    - git remote add github_waldur $GITHUB_WALDUR_REPO_URL || true
    - git remote -v
    - pip install -r requirements.txt
    - export ENABLE_PDF_EXPORT=1
    - mkdocs gh-deploy --force -r github_opennode
  before_script:
    - echo "[+] Adding ssh keys to the home directory"
    - mkdir -p ~/.ssh
    - cat $SSH_JENKINS_GITHUB_PRIVATE_KEY | tr -d '\r' > ~/.ssh/id_rsa
    - cat $SSH_JENKINS_GITHUB_PUBLIC_KEY | tr -d '\r' > ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa.pub
    - ssh-keygen -lf ~/.ssh/id_rsa.pub
    - ssh-keyscan -H "github.com" >> ~/.ssh/known_hosts
