site_name: Waldur Documentation
site_description: Documentation of an open-source marketplace platform Waldur. See the latest version at https://docs.waldur.com
theme:
  name: material
markdown_extensions:
  - meta
  - attr_list
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
google_analytics:
  - UA-34543419-4
  - auto
plugins:
  - search
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
  - git-revision-date
  - render_swagger
  - print-site:
      print_page_title: 'Print documentation'
      enumerate_headings: true
      add_cover_page: true
      exclude:
        - user-guide/
        - user-guide/*
copyright: Copyright &copy; 2016 - 2021 Waldur team
