site_name: Waldur Documentation
site_description: Documentation of an open-source marketplace platform Waldur. See the latest version at https://docs.waldur.com
theme:
  name: material
  palette:
    primary: green
  analytics:
    gtag: G-5M7QPTQT8H
  logo: assets/waldur-logo.svg
  favicon: assets/waldur-logo.svg
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date
  - render_swagger
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - print-site:
      print_page_title: 'Print documentation'
      enumerate_headings: true
      add_to_navigation: true
      add_cover_page: true
      exclude:
        - API/
        - API/*
copyright: Copyright &copy; 2016 - 2024 Waldur team
